### ISSUE TITLE
unneeded div

### ISSUE THREAD

**Issue by rimmesbe** [kirakID/prj-rev-bwfs-tea-cozy#1]
There is no need for the `<div class="nav">` you aren't even using it in the css. It ruins the point of the `<nav>` which is also a div just with a semantic name.

https://github.com/kirakID/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/index.html#L13

**Comment by kirakID** [comment]
Thanks Ryan,

I thought we needed to use the divs to make the boxes. and also because at the beginning I had all the divs show up as a white border, so that I could see how they would align.
