### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [kirakID/prj-rev-bwfs-tea-cozy#6]
Grade: Exceeds expectations

Summary: Really nice job on this project, end result looks good. You used a lot of good techniques and I was impressed by your css efficiency. The main issues I found was with organization: extra divs, unnecessary classes, maybe an over use of id's. Check out the issues I made and see if they make sense. Overall really nice job, you are ready for Responsive design. 
Article regarding different position types: https://internetingishard.com/html-and-css/advanced-positioning/

**Comment by kirakID** [comment]
Thank you,
It took a LOT of trial and error and to be honest I am not 100% sure how all of this works. The chat tech support has been GREAT. I made the suggested changes to the code on my local computer. 
Thanks again.
